### PR TITLE
add opacity to paint

### PR DESCRIPTION
**Pull request by conversy**
this enables to control the overall opacity without changing the color or all stop colors in a gradient.It adds a multiply operation in the shader though.

### CODE REVIEW

**Comment by mokafolio** [comment]
Hi,

I think this is a useful addition. Can I suggest the following things before merging though:

For solid paints, compute the color on the cpu (i.e. color * opacity) before setting the uniform on the shader.

For gradients, pass opacity as a separate uniform. Only read the uniform in the fragment shader. There is no point in reading it in the vertex shader and passing it along. 

Hope that makes sense! Thanks for contributing!

**Comment by conversy** [comment]
for solid: ok for the compute on the cpu. Do you want me to change the patch? I'm not sure how I can do that (not that knowledgeable with github), but I can try...

**Comment by mokafolio** [comment]
All good, thank you! I merged it into a separate branch for now. I'll have a stab at the changes I suggested above throughout the day and then merge it into master.

**Comment by mokafolio** [comment]
Just did all the changes. I decided to only add an extra opacity field if gradients are used. I added `tpPaintSetOpacity` and `tpPaintOpacity` if you want to control paint opacity in a type independent way. Also cleaned up the texture/gradient shader in that regard. Initial commit for all of that is here: https://github.com/mokafolio/Tarp/commit/49d005af281c029919dcef1761222d019e8fb55d

**Comment by conversy** [comment]
I could cope with your changes. Actually, in my use, sometimes Opacity is set before Color, and I do not know if it will be a solid color or a gradient. So I had to take that into account. I ended up to something like this, provided that alpha is 1.0 by default:

tpPaintSetOpacity(&style.fill, tpPaintOpacity(&style.fill) * alpha); // in case paint has been set before
or
style.fill = tpPaintMakeColor(r/255.f, g/255.f, b/255.f, tpPaintOpacity(&style.fill)); // in case opacity has been set before

This was not required with my original commit, but I think it works.

Btw, don't your (legitimate) remark on useless uniform in the vertex shader apply for meshColor as well?

**Comment by mokafolio** [comment]
Yes, good catch! I think the original version of the shader also had per vertex colors which were multiplied by the mesh color. I will change that!

Regarding the opacity. I actually think I might remove the opacity functions for the reason you are describing above. (You'd have to explicitly set the gradient opacity instead)
I'd like to keep it that way to reduce ambiguity and not having to carry around an extra float in `tpPaint` that will almost never be used in the solid color case. Does that make sense?

**Pull request merged**
